### ISSUE TITLE
After improved3.fasta creation, finisherSC continues to run for >12hrs on 20 cores

### ISSUE THREAD

**Issue by EarlyEvol** [kakitone/finishingTool#13]
Hello,

I have been testing finisherSC on a wasp genome assembly of about 360mb with ~30X PacBio data.  It took about 4 days to run with several restarts.   It errored out three times because a lack of memory, at 168, 300, and 600gb.  Interestingly after restart on a cluster with 1TB it ran just fine...but never used more than 30gb.  The final restart picked up with the improved2.fasta.  Is this massive RAM usage normal?  Why would it use 600gb then only 30 to repeat the same tasks?

In the end the script was interrupted again, this time because of exceeding my walltime.  Interestingly, 12hrs before the script timed out, it finished writing the improved3.fasta.  The assembly looks complete, with only 20 less scaffolds, approximately the same size, and a slight improvement in n50 from improved2.fasta. I couldn't find anything in the stderr/out that indicated it wrote to improved3.fasta though.
The final lines of stderr/out show that it was still doing some aligning:
\# matching query-file "/home/SAMPLE_finisherSC.1/improvedtmp.part-06.fasta
\# against subject-file "/home/SAMPLE_finisherSC.1/improved.fastafillmiss0506.ntref"
=>> PBS: job killed: walltime 86418 exceeded limit 86400

Any help would be appreciated. 

Thanks,
Earl

**Comment by EarlyEvol** [comment]
Well, after some digging, I think I have answered my own question in terms of finisherSC continuing to run after improved3.fasta being written.  It looks like by default it moves on to xPhaser.  Is this correct?  Here is a snippet of the stdout:

All contigs used?  True
NContig 1946
xPhased  
/home/u14/earlm1/WorkingDir/assemblies/Lb17_finisherSC.1/tmp_contigs.fasta: 2126 sequences, 352644748 bp => dividing into 10 parts .......... OK
All done, 63 seconds elapsed
/home/u14/earlm1/WorkingDir/assemblies/Lb17_finisherSC.1/noEmbedtmp.fasta: 2106 sequences, 352511548 bp => dividing into 10 parts .......... OK

Since the number of contigs in improved3.fasta is 1946, it seems likely that this is where it wrote improved3.fasta.  

I still have no idea about the RAM usage mentioned in the first post though.

**Comment by kakittwo** [comment]
Since improvedtmp.fasta is generated, the whole pipeline is mostly done. 

The remaining step is to compare the improved.fasta , improved2.fasta , improved3.fasta to the input contigs to double check if any contigs were mistakenly missed. And if that happen, they will be added back to the improved*.fasta correspondingly.

**Comment by kakittwo** [comment]
As for the RAM usage, I think it may be related to the operations of MUMmer. They build some data structure initially for fast query subsequently. My guess is that they may request certain upper bound on RAM based on some worse case analysis but end up using less because of the structure of the genome being assembled.

**Comment by EarlyEvol** [comment]
Wow, thanks for the super fast reply.

Ah, I see, can I restart from that spot, or do i need to regenerate all the intermediate files that were created after improved3.fasta, i.e. improved.fastafillmiss*.mgaps, noEmbed.fastafillmiss*.delta and so forth.

Do I just use "-p improved3.fasta" to restart?

Thanks again!

**Comment by kakitone** [comment]
You can restart from that spot and do not need to regenerate intermediate files after improved3.fasta

If you comment out line 18 to line 28 in finishingTool/finisherSC.py and restart, it will pick up the process. In that case, you do not need -p improved3.fasta because you have commented out the previous steps.

**Comment by EarlyEvol** [comment]
thanks so much!  i just fired it up.
